# -*- coding: utf-8 -*-
"""test tuto2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j_nPTpF22vsy-h_cIIYPpl4BCJFeZnGS
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline

start = '2015-01-01'
end = '2020-12-31'

import yfinance as yf
Stock1 = yf.download ("AAPL", start=start, end =end)
Stock2 = yf.download ("BABA", start=start, end =end)
Stock3 = yf.download ("TSLA", start=start, end =end)

Crypto1 = yf.download ("BTC-USD", start=start, end =end)
Crypto2 = yf.download ("ETH-USD", start=start, end =end)
Crypto3 = yf.download ("SOL-USD", start=start, end =end)

Stock1.to_csv('aapl_stock.csv')

print('Number of variables: {}'.format (AAPL.shape[1]))
print('Number of rows: {}'.format(AAPL.shape[0]))

Stock1['Close'].max()

Stock1['Close'].min()

AAPL['Close'].plot(label='Apple', figsize=(16,8))
BABA['Close'].plot(label = 'Alibaba', figsize=(16,8))
plt.xlabel("date")
plt.ylabel("$ price")
plt.title ("Apple Stock price 1/1/2015-31/12/2020")
plt.legend();

#Facebook, Amazon, Apple, Netflix, Google
tickers = ["FB", "AMZN", "AAPL", "NFLX", "GOOG"]
portfolio = yf.download (tickers, start, end)

portfolio['Close']

AAPL['Close'].plot(label = 'Apple', figsize =(16,8))
plt.xlabel("date")
plt.ylabel("$ price")
plt.title ("Apple Stock price 1/1/2015 - 31/12/2020")
plt.legend()
plt.savefig("pic.png")